### ISSUE TITLE
How to get the docker hub image?

### ISSUE THREAD

**Issue by 454076513** [compound-finance/gateway#322]
Hi, I want to startup the image. but I do not have permission to pull. 
`Error response from daemon: Get https://docker.pkg.github.com/v2/compound-finance/gateway/run-on-arch-compound-finance-compound-chain-upload-release-asset-aarch64-ubuntu18-04/manifests/latest: no basic auth credentials`.
Can you upload it to docker hub?

**Comment by jflatow** [comment]
This was a testing image someone had built - not an official artifact - thanks for flagging so we could remove. We aren't generating docker builds yet
