### ISSUE TITLE
Comp gateway fails to compile with latest rust nightly release (rustc 1.54.0-nightly)

### ISSUE THREAD

**Issue by steve0xp** [compound-finance/gateway#328]
### Error Details
**Context:** booting up a validator node on local machine. The latest rust nightly release seems to cause issues with COMP Gateway compilation. Tried with two separate local machines, and an AWS instance. Error arose when building the compound chain release binary when running command:

``
cargo +nightly build --release
``

### Error that Arises:

 ```
 error[E0557]: feature has been removed
    --> /Users/steve/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.2/src/lib.rs:42:43
     |
  42 | #![cfg_attr(not(feature = "std"), feature(const_fn))]
     |                                           ^^^^^^^^ feature has been removed
     |
     = note: split into finer-grained feature gates

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0557`.
  error: could not compile `environmental`

  To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**I believe compilation works if you downgrade to a lesser rust version currently.**

Awesome job with everything your team is working on here! 😄

**Comment by xlc** [comment]
`cargo update -p environmental` should fix it. someone will need to PR the Cargo.lock change

**Comment by steve0xp** [comment]
Thanks! Just to keep you/the team updated, I ran it with your suggested command and it worked for my local machine (MacBook Pro w/ M1 Chip). I also went ahead and ran it with an AWS instance, and the errors I was getting there were resolved as well. I'll leave the issue here for the team to close following their procedures! Cheers!
